layout_spectrum: 0.15623129361244564
typography_spectrum: 0.20355693860680307
color:
  brandStrength: 0.10981171174657227
  lightness: 0.4321618478309068
  saturation: 0.7509392196736714
  rhythmicContrast: 0.3288840300438575
  brandColors:
    - '#F7F2B2'
    - '#ADCF4F'
    - '#84815B'
    - '#4A1A2C'
    - '#8E3557'
github: true
author:
  name: Sage Pintor
  email: sagepintor@gmail.com
name: WebWiser
title: Web Wiser
content: []
description: We want to help you Web Wiser
purpose:
  - type: contact
    url: 'mailto:sagepintor@gmail.com'
    label: Contact me
